# this is a sample of config file.
# remove prefix '_' of 'config.toml' if you want to use it

[database]
address = "your.database.host"
user = "your.username"
password = "your.password"
name = "your.database.name"

[app]
version = "2021.xxxx.xxxx"      # should be rewritten by 'main.py' with the modify time of itself.
DEFAULT_TEAMS_STRING = '勇士,北京,北控,掘金,热刺,埃弗顿,F1,皇家马德里'
GRAB_INTERVAL = 1800    # how many second the grabbed page expires, for a sports game, half an hour should be OK.
GRAB_TIMER_BASE = 1800  # grab interval would be between GRAB_TIMER_BASE and TIMER_RANDOM_SEED + GRAB_TIMER_BASE
TIMER_RANDOM_SEED = 1800    # in this case, it should be in 1800s - 3600s (30min - 60min) and, in product env, there is 4 workers at least, so there would be 4 times more hit rate.